FLAGS = -g
#FLAGS = -O2

all: test_Bidon test_GrupoBidones test_Jugprob test_Leer test_Main test_Menu test_OperacionLlenar test_OperacionTrasvasijar test_OperacionVaciar

test_Bidon:

test_GrupoBidones:

test_Jugprob:

test_Leer:

test_Main:

test_Menu:

test_OperacionLlenar:

test_OperacionTrasvasijar:

test_OperacionVaciar: