FLAGS = -g
#FLAGS = -O2

all: test_Bidon test_GrupoBidones test_Jugprob test_Leer test_Main test_Menu test_OperacionLlenar test_OperacionTrasvasijar test_OperacionVaciar

test_Bidon:
	g++ ${FLAGS} ? -o test_Bidon

test_GrupoBidones:
	g++ ${FLAGS} ? -o test_GrupoBidones

test_Jugprob:
	g++ ${FLAGS} ? -o test_Jugprob

test_Leer:
	g++ ${FLAGS} ? -o test_Leer

test_Menu:
	g++ ${FLAGS} ? -o test_Menu

test_OperacionLlenar:
	g++ ${FLAGS} ? -o test_OperacionLlenar

test_OperacionTrasvasijar:
	g++ ${FLAGS} ? -o test_OperacionTrasvasijar

test_OperacionVaciar:
	g++ ${FLAGS} ? -o test_OperacionVaciar



clean:
	rm -f *.o test_Bidon test_GrupoBidones test_Jugprob test_Leer test_Main test_Menu test_OperacionLlenar test_OperacionTrasvasijar test_OperacionVaciar